### ISSUE TITLE
zero-width breaking space support

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/trim-right#2]
https://en.wikipedia.org/wiki/Zero-width_space

dunno if it's on par with your spec-compliant issue, though.

**Comment by sindresorhus** [comment]
Doesn't look like it, though I may be interpreting it wrongly:

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-string.prototype.trim

> The definition of white space is the union of WhiteSpace and LineTerminator.

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-white-space

**Comment by stevenvachon** [comment]
hmm, how about

> Other category “Zs”   Any other Unicode “Separator, space” code point

with regards to the second link.

If `U+FEFF` consecrates a "union of whitespace and line termination", then so should `U+200B`

**Comment by sindresorhus** [comment]
``` js
'\u200B'.trim().length
//=> 1
```

Wrong place to argue the spec. Try: https://esdiscuss.org/1
